# ====================================
# CONFIGURACIÓN DESARROLLADOR (DEV)
# ====================================
spring.datasource.url=your_local_host:xxxx/wallet_db
spring.datasource.username=your_postgres
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver